fix(Kotlin/JS): replace deprecated Kotlin/JS IR compiler API with a n…
JetBrains/kotlin-compiler-server pull request #508
Opened 2022-07-04 18:26 UTC by JSMonk

The PR provides a new way to compile JS with IR.
The currently used API will be removed from the compiler soon, so the provided changes will prevent breaks on the compiler API side.

2022-10-20 14:17 UTC, AlexanderPrendota commented
should I merge it? =)

2022-10-21 05:53 UTC, JSMonk commented
Sure. We've just started to delete the described API, so, it will be great if we will merge it before compiler updates that will not contain deprecated API.

2022-10-21 11:37 UTC, AlexanderPrendota commented
Okay, do we need to have test for such changes?

2022-10-21 11:38 UTC, AlexanderPrendota requested changes

2022-10-21 11:38 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    val jsCode = compiledModule.outputs[translationMode]!!.jsCode
is it possible to avoid using `!!`?

2022-10-25 20:24 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    val jsCode = compiledModule.outputs[translationMode]!!.jsCode
cc @JSMonk

2022-10-31 15:20 UTC, AlexanderPrendota commented
@JSMonk ping

2022-11-15 13:13 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    val jsCode = compiledModule.outputs[translationMode]!!.jsCode
yes, let's do it

2022-11-21 18:08 UTC, AlexanderPrendota commented
@JSMonk friendly ping

2023-06-19 12:06 UTC, closed without merging