KTL-114 Add kotlinx.serialization compiler plugin to Kotlin Playground
JetBrains/kotlin-compiler-server pull request #540
Opened 2022-09-06 16:06 UTC by nikpachoo

There is a draft for supporting kotlinx.coroutines.

2022-09-07 14:03 UTC, AlexanderPrendota requested changes

2022-09-07 14:03 UTC, AlexanderPrendota commented on common/src/main/kotlin/component/KotlinEnvironment.kt
> +    if (compilerPlugins.isNotEmpty()) {
is it possible to pass arguments only if we need plugins?

2022-09-09 14:31 UTC, nikpachoo commented on common/src/main/kotlin/component/KotlinEnvironment.kt
> +    if (compilerPlugins.isNotEmpty()) {
Sorry, I am not sure what you mean. 
The arguments are passed only if the plugin was defined if the build.gradle.kts.
So, for me, it is what you asked for :)

2022-09-11 22:38 UTC, AlexanderPrendota commented on common/src/main/kotlin/component/KotlinEnvironment.kt
> +    if (compilerPlugins.isNotEmpty()) {
it's not necessary to have compiler plugins if we don't use them in the code

2024-08-27 15:59 UTC, closed without merging