KTL-1017 Compiler-Server: unify version definition
JetBrains/kotlin-compiler-server pull request #633
Opened 2023-05-04 20:56 UTC by nikpachoo

https://youtrack.jetbrains.com/issue/KTL-1017/Compiler-Server-unify-version-definition

2023-05-05 11:51 UTC, zhelenskiy requested changes

2023-05-05 11:51 UTC, zhelenskiy commented on docker-image-build.sh
> +kotlin_version=$(grep "systemProp.kotlinVersion" gradle.properties | cut -d'=' -f2)
`awk '{ if ($1=="systemProp.kotlinVersion") { print $2; } }' FS='=' ./gradle.properties` seems to be better solution.

2023-05-05 11:55 UTC, nikpachoo commented on docker-image-build.sh
> +kotlin_version=$(grep "systemProp.kotlinVersion" gradle.properties | cut -d'=' -f2)
updated

2023-05-05 11:56 UTC, zhelenskiy approved these changes

2023-05-05 11:58 UTC, nikpachoo commented on gradle.properties
> +systemProp.kotlinIdeVersionSuffix=IJ4167.29
@woainikk, JFI this version is now also in the configuration file.

2023-05-09 09:30 UTC, woainikk approved these changes

2023-05-09 10:31 UTC, merged